import './App.css';
function App() {
    return (
        <div>
            <div>Aplikacja BW Øè•Øè∆</div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lobortis, purus at iaculis congue, metus metus efficitur mi, at bibendum eros arcu ornare lectus. Aliquam erat volutpat. Mauris id suscipit risus, et iaculis nisl. Sed sollicitudin, arcu sed accumsan blandit, quam elit dapibus purus, non tincidunt augue turpis in mi. Vivamus pretium justo euismod porta sagittis. Ut fermentum arcu nec nulla vulputate dignissim. Cras et pretium ipsum, et porttitor sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus non metus enim. Aenean porttitor mi metus, vel ultricies ante bibendum eget. Donec purus elit, efficitur sed enim in, efficitur accumsan odio. Donec lacinia elit lectus, nec interdum arcu euismod in. Sed id iaculis diam. Fusce urna turpis, lacinia rutrum lorem vitae, tempor sodales ligula. Praesent arcu augue, volutpat sit amet erat nec, auctor luctus nunc.

                Nulla scelerisque dignissim neque, ut suscipit metus rutrum non. Integer aliquet elit aliquet luctus viverra. Aenean ornare finibus porta. Phasellus massa orci, pretium et risus et, vehicula vestibulum lacus. Ut viverra tortor libero, nec elementum velit aliquet vel. Pellentesque rhoncus rhoncus elit, vel aliquet tellus fringilla eu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla facilisi. Sed aliquet dolor nec tristique sagittis. Duis quis rhoncus diam, imperdiet tempus diam. Vestibulum mi dui, gravida sit amet dictum id, congue sed eros. Quisque malesuada leo sed pharetra malesuada. Nulla id mauris in enim bibendum ultrices.

                In maximus vehicula semper. Nunc at erat ut urna euismod scelerisque sed eu lacus. Maecenas tempus mollis bibendum. Etiam tempus pellentesque eros vel sagittis. Cras at velit turpis. Nam ac est vitae risus facilisis accumsan. Vivamus vel nunc vel velit posuere dapibus vitae scelerisque enim. Sed iaculis sed nunc eu pulvinar. Nulla at risus nisl. Nulla tempor elit sed cursus iaculis. Morbi a tortor quis est ullamcorper faucibus nec eu orci. Donec risus sem, rutrum sit amet odio nec, sodales egestas risus. Fusce faucibus tristique dictum.

                Etiam at dictum ipsum. Cras elementum felis a interdum ultricies. Vivamus vulputate arcu in est ultricies, vitae mollis ante condimentum. Curabitur tristique, elit non dignissim accumsan, erat ante viverra sem, non pretium elit turpis sed ex. Praesent diam risus, luctus sit amet aliquet a, dignissim eget massa. Praesent sit amet lacus nibh. Integer porta, neque laoreet tristique sodales, nisi libero placerat massa, eget accumsan odio risus in est. Aenean dictum feugiat risus, id faucibus augue sagittis non. Maecenas at libero et turpis pulvinar egestas. Duis tincidunt urna eu ultrices accumsan. Curabitur diam urna, mattis ac aliquet vitae, dapibus non risus. Nam eu lectus suscipit, mollis purus sit amet, vulputate ante. Phasellus quis lobortis sem. Mauris vulputate consequat fringilla. In ut condimentum sem. Donec egestas metus sit amet nulla dapibus, vitae congue sem varius.

                Aenean eget risus ut massa feugiat elementum. Morbi mattis tellus eu lacus pharetra iaculis. Fusce pulvinar lacus viverra nulla rutrum aliquam rutrum ut odio. Donec sit amet arcu hendrerit risus scelerisque sodales vel et nulla. Suspendisse non leo a sem eleifend tristique. Fusce non vehicula turpis, non vulputate nisl. Nullam vestibulum laoreet gravida. Donec scelerisque mattis dignissim.</p>
        </div>
    );
}

export default App;